FILE_TYPE_XML='xml'

MANIFEST_XML='<?xml version="1.0" encoding="UTF-8"?>'
MANIFEST_PACKAGE='<Package xmlns="http://soap.sforce.com/2006/04/metadata">'
MANIFEST_PACKAGE_CLOSE='</Package>'
MANIFEST_TYPES='<types>'
MANIFEST_TYPES_CLOSE='</types>'
MANIFEST_NAME='<name>'
MANIFEST_NAME_CLOSE='</name>'
MANIFEST_MEMBERS='<members>'
MANIFEST_MEMBERS_CLOSE='</members>'
MANIFEST_API_VERSION_53='<version>53.0</version>'